language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
sudo: false
cache:
- pip
install:
- pip install -r requirements-test.txt -e .
- pip install coveralls
script: python setup.py test
after_success:
- coveralls
notifications:
  slack:
    rooms:
      secure: ...
deploy:
  provider: pypi
  user: frankv
  password:
    secure: ...
  on:
    tags: true
    repo: frankv/flask-sendgrid